services:
  komga:
    image: ghcr.io/gotson/komga:latest
    container_name: komga
    networks:
      - komga
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: ./data
        target: /data
        read_only: true
    ports:
      - 4002:25600
    user: 1000:1000
    environment:
      - TZ=Europe/Paris

networks:
  komga:
